"""first DB migration

Revision ID: c8b1da291972
Revises:
Create Date: 2026-10-02 23:57:46.697414

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8b1da291972"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "bed",
                "gameready_feet",
                "gameready_thighs",
                "compression_lower_body",
                "heat",
                "cold",
                "ice_bath",
                name="resource_type",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_quantity > 0", name="ck_resources_total_quantity_positive"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_resources_name"),
        sa.UniqueConstraint("type", name="uq_resources_type"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "role", sa.Enum("physio", "client", name="user_role"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("physio_notes", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "confirmed",
                "cancelled_by_client",
                "cancelled_by_physio",
                "completed",
                "no_show",
                name="appointment_status",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_time > start_time", name="ck_end_time_posterior_start_time"
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "appointment_resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "appointment_id",
            "resource_id",
            name="uq_appointment_resources_appointment_id_resource_id",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appointment_resources")
    op.drop_table("appointments")
    op.drop_table("users")
    op.drop_table("resources")
    # ### end Alembic commands ###
